### ISSUE TITLE
DMS test migration mentions a .tar file on github

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-dms-step-by-step#1]
Hello,
On https://github.com/awsdocs/aws-dms-step-by-step/blob/master/doc_source/CHAP_On-PremOracle2Aurora.Appendix.SampleDatabase.md there's a mention of .tar file to download on github. Issue is: there's no .tar file. Of course there are scripts but the instructions are probably out-of-date ?

**Comment by overhere00** [comment]
Thank you for letting us know about this (and apologies for the delay) - we'll fix this and republish soon.
