### ISSUE TITLE
Oracle_Redshift_For_DMSDemo.yml is old

### ISSUE THREAD

**Issue by Yuhta28** [awsdocs/aws-dms-step-by-step#7]
# template issue
CloudFormation template for chap-rdsoracle2redshift.steps is old.
http://docs.aws.amazon.com/dms/latest/sbs/samples/dms-sbs-RDSOracle2Redshift.zip

I used this template and attemplted to create stack.
But, I failed to create stack.
![image](https://user-images.githubusercontent.com/54278643/126030916-1bc4dffa-cd31-445f-b107-e40aa56a247b.png)

According to "Status reason" message,  DB instance type is former version, "db.m3~".
I fixed template file to change former instance type to now instance type.
[dms-sbs-RDSOracle2Redshift.zip](https://github.com/awsdocs/aws-dms-step-by-step/files/6834412/dms-sbs-RDSOracle2Redshift.zip)

**Comment by ndrivan** [comment]
Updated the template on https://docs.aws.amazon.com/dms/latest/sbs/chap-rdsoracle2redshift.steps.launchrdswcloudformation.html.
